# Implementation ANN 

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("/kaggle/input/50-startups/50_Startups.csv")

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [7]:
x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [8]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)


In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [10]:
x_train.shape

(40, 6)

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [12]:
regressor = Sequential()

In [13]:
x_train.shape

(40, 6)

In [15]:
regressor.add(Dense(units = 6,kernel_initializer = 'random_uniform',activation = 'relu'))

In [16]:
regressor.add(Dense(units = 12,kernel_initializer = 'random_uniform',activation = 'relu')) # 1st hidden layer

In [17]:
regressor.add(Dense(units = 8,kernel_initializer = 'random_uniform',activation = 'relu')) # second hiden layer

In [18]:
regressor.add(Dense(units = 9,kernel_initializer = 'random_uniform',activation = 'relu')) # third Hidden layer

In [19]:
regressor.compile (optimizer = 'adam',loss = 'mse',metrics = ['mse'])

In [20]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 300)

Epoch 1/300
4/4 [==============================] - 1s 5ms/step - loss: 13615934464.0000 - mse: 13615934464.0000
Epoch 2/300
4/4 [==============================] - 0s 3ms/step - loss: 13615797248.0000 - mse: 13615796224.0000
Epoch 3/300
4/4 [==============================] - 0s 3ms/step - loss: 13615534080.0000 - mse: 13615534080.0000
Epoch 4/300
4/4 [==============================] - 0s 3ms/step - loss: 13615128576.0000 - mse: 13615129600.0000
Epoch 5/300
4/4 [==============================] - 0s 2ms/step - loss: 13614411776.0000 - mse: 13614411776.0000
Epoch 6/300
4/4 [==============================] - 0s 2ms/step - loss: 13613267968.0000 - mse: 13613267968.0000
Epoch 7/300
4/4 [==============================] - 0s 3ms/step - loss: 13611476992.0000 - mse: 13611476992.0000
Epoch 8/300
4/4 [==============================] - 0s 2ms/step - loss: 13608324096.0000 - mse: 13608324096.0000
Epoch 9/300
4/4 [==============================] - 0s 2ms/step - loss: 13604014080.0000 - mse: 136040140

In [21]:
y_pred = regressor.predict(x_test)

1/1 [==============================] - 0s 91ms/step


In [22]:
y_pred

array([[119375.945,      0.   , 119364.45 , 119379.19 ,      0.   ,
        119366.77 ,      0.   , 119372.09 , 119375.05 ],
       [118811.16 ,      0.   , 118801.77 , 118815.45 ,      0.   ,
        118804.06 ,      0.   , 118808.9  , 118810.89 ],
       [124660.12 ,      0.   , 124649.695, 124664.32 ,      0.   ,
        124652.11 ,      0.   , 124657.32 , 124659.664],
       [ 63949.02 ,      0.   ,  63944.887,  63951.785,      0.   ,
         63946.055,      0.   ,  63948.45 ,  63949.164],
       [169169.12 ,      0.   , 169156.64 , 169175.7  ,      0.   ,
        169159.88 ,      0.   , 169166.58 , 169169.02 ],
       [124575.43 ,      0.   , 124567.766, 124581.03 ,      0.   ,
        124570.05 ,      0.   , 124574.64 , 124575.836],
       [ 54230.52 ,      0.   ,  54227.93 ,  54233.33 ,      0.   ,
         54228.883,      0.   ,  54230.71 ,  54230.92 ],
       [102414.87 ,      0.   , 102404.7  , 102417.49 ,      0.   ,
        102406.71 ,      0.   , 102411.336, 102414.   ],


In [23]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [32]:
regressor.save('regressor.h5')

In [30]:
x_train.shape

(40, 6)

In [31]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

1/1 [==============================] - 0s 59ms/step


array([[59338.52 ,     0.   , 59332.805, 59340.133,     0.   , 59333.98 ,
            0.   , 59336.62 , 59338.07 ]], dtype=float32)