# Implementation : Churn-model

In [1]:
# imports
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/kaggle/input/churn-modelling/Churn_Modelling.csv")

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
data['Geography'].fillna(data['Geography'].mode()[0],inplace = True)
data['Age'].fillna(data['Age'].mean(),inplace = True)
data['Balance'].fillna(data['Balance'].median(),inplace = True)

In [7]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
p = data['Geography'].mode()

In [9]:
p

0    France
Name: Geography, dtype: object

In [10]:
p[0]

'France'

In [11]:
data['Geography'].mode()[0]

'France'

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Geography'] = le.fit_transform(data['Geography'])
# - 0 --some
# - 1 some 
# - 2 somee


In [13]:
data['Gender'] = le.fit_transform(data['Gender'])

#mee - 1
#female -0



In [15]:
data.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

india - 2
japan  - 3
switze -4
germany -1
australia - 0


In [16]:
x = data.iloc[:,3:13].values

In [17]:
y = data.iloc[:,13].values

In [18]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [19]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [20]:
type(y)

numpy.ndarray

In [21]:
x.shape

(10000, 10)

In [22]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()






In [23]:
x = np.delete(x,1,axis = 1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [24]:
x = np.concatenate((z,x),axis = 1)

In [25]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
# more number of one hot encoding value 
z =  one.fit_transform(x[:,3:4]).toarray()
t =  one.fit_transform(x[:,5:6]).toarray()
u =  one.fit_transform(x[:,9:10]).toarray()
x = np.delete(x,[3,5,9],axis = 1)
x = np.concatenate((z,t,u,x),axis = 1)


india - 2
japan  - 3
switze -4
germany -1
australia - 0

australia germany india  japan switz
0          0       1       0      0
0          0       0       1      0
0          0        0      0      1



In [28]:
x.shape

(10000, 541)

In [29]:
y.shape

(10000,)

In [30]:
#split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [31]:
x_test.shape

(2000, 541)

In [32]:
y_test.shape 

(2000,)

In [33]:
x_train.shape 

(8000, 541)

In [34]:
y_train.shape

(8000,)

In [36]:
x1  = np.array([1,2,3,4,5,6,7,8,9])
y1 = np.array([0,1,0,1,0,1,0,1,0])

In [37]:
from sklearn.model_selection import train_test_split
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2)
    
    print ("x_trainwithout random state for the iteration" ,i,x_train)
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2, random_state = 0)
    
    print ("x_train  with random state for the iteration" ,i,x_train)
    

x_trainwithout random state for the iteration 0 [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.0000000e+00
  0.0000000e+00 1.6383064e+05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 5.7098000e+04]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.8563076e+05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.0000000e+00
  0.0000000e+00 1.8142987e+05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.0000000e+00
  1.0000000e+00 1.4875016e+05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1885526e+05]]
x_trainwithout random state for the iteration 1 [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.0000000e+00
  0.0000000e+00 1.6383064e+05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 5.7098000e+04]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.8563076e+05]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.000000

In [38]:
x_train[:,5:10]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [40]:
x_train.shape

(8000, 541)

In [50]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential



In [51]:
model = Sequential()
model.add(Dense(units=12, kernel_initializer="random_uniform", activation="relu"))


In [52]:
model.add(Dense(units = 1, kernel_initializer = "random_uniform",activation = "sigmoid"))

In [53]:
model.compile(optimizer = "adam",loss = "binary_crossentropy", metrics = ["accuracy"])

In [54]:
model.fit(x_train,y_train,batch_size = 32 , epochs = 500 )

Epoch 1/500
250/250 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7780
Epoch 2/500
250/250 [==============================] - 0s 2ms/step - loss: 0.4326 - accuracy: 0.7960
Epoch 3/500
250/250 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.7960
Epoch 4/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3910 - accuracy: 0.7960
Epoch 5/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3818 - accuracy: 0.8281
Epoch 6/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3731 - accuracy: 0.8379
Epoch 7/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3653 - accuracy: 0.8422
Epoch 8/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3574 - accuracy: 0.8484
Epoch 9/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8546
Epoch 10/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3413 - accura

In [55]:
y_pred  = model.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [56]:
y_pred

array([[1.4992123e-03],
       [7.1292073e-01],
       [9.9998230e-01],
       ...,
       [0.0000000e+00],
       [7.4893974e-02],
       [3.6793763e-20]], dtype=float32)

In [57]:
y_pred = (y_pred > 0.5)

In [58]:
y_pred

array([[False],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [59]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

 to increasee the accurracy 
* add more hidden layers
* add more epochs



### models performance is really good as now 